export const services = [
  { path: "/kitchen-fitting", title: "Kitchen Fitting in Northern Ireland", image: "/projects/kitchen51.jpeg", description: "Kitchen installation across Northern Ireland, with supplier plan review, cabinet fitting, finishing and coordination of agreed trades.", intro: "Already chosen your kitchen? DC Joinery can review your supplier plans and discuss the installation, preparation and finishing needed for your room.", sections: [
    ["Plans and preparation", "Send the supplier drawings, room measurements and postcode with your enquiry. Cabinet sizes, appliance spaces, worktop arrangements and access all help define the fitting scope before work starts."],
    ["Cabinets and finishing", "Installation can include flat-pack or assembled cabinets, alignment, doors, panels and finishing details. Removal, flooring and tiling are agreed separately so the quotation clearly describes the work included."],
    ["Trades and scheduling", "Electrical, plumbing and gas connections need the appropriate qualified trades. We discuss coordination and the sequence of work, including any separate worktop templating and installation."],
  ], questions: [["Can you fit a kitchen I have already bought?", "Yes. Send the plans and details of what has been ordered so we can review the installation requirements."], ["Which suppliers feature in your work?", "Our portfolio includes Wren, Howdens, IKEA, B&Q and bespoke kitchens. The requirements depend on the specific supplier and room."], ["How long will fitting take?", "Timing depends on the kitchen, preparation, worktops and trade availability. We discuss a project-specific schedule rather than promise a fixed duration before reviewing the plans."]] },
  { path: "/fit-and-supply", title: "Kitchen Supply & Installation in Northern Ireland", image: "/projects/kitchen46.JPG", description: "Discuss kitchen design, supplier options, ordering and installation with DC Joinery in Northern Ireland.", intro: "A kitchen project starts with how you use the room, the storage you need and the budget you want to work within. We help bring the design, supply and installation stages together.", sections: [
    ["Choosing your kitchen", "Discuss your room layout, appliance requirements and preferred finishes. Supplier options, product availability and final measurements must be confirmed before an order is placed."],
    ["Agreeing the scope", "The quotation should identify the kitchen supply, removal, room preparation, fitting and finishing that are included. Flooring, tiling and specialist connections are discussed alongside the main installation."],
    ["Ordering and installation", "Delivery, preparation, fitting and worktop installation need a coordinated sequence. Changes to the agreed design or scope should be confirmed before proceeding."],
  ], questions: [["Do I need to choose a kitchen before contacting you?", "No. Tell us about the room, your priorities and preferred budget to start the discussion."], ["Can the AI designer provide the final kitchen plan?", "The AI designer produces an illustrative concept. A measured survey and supplier specifications are required for a final design and quotation."], ["Can removal and flooring be included?", "We can discuss these as part of the project. The written quotation confirms the work included."]] },
  { path: "/fitted-bedrooms", title: "Fitted Bedrooms & Wardrobes in Northern Ireland", image: "/projects/kitchen18.jpeg", description: "Fitted wardrobes, bedroom storage and built-in furniture tailored to your room and storage needs in Northern Ireland.", intro: "Make better use of your room with fitted wardrobes and built-in storage. We discuss shelving, hanging space and the layout that suits your everyday needs.", sections: [
    ["Storage designed around the room", "Room dimensions, ceiling height, windows and services affect the available space. Send photographs and approximate measurements so we can discuss a practical layout."],
    ["Shelving and hanging space", "The balance of shelves, hanging space and accessible storage depends on what you need to keep in the room. Finishes and fitting details are agreed with the proposed design."],
    ["See existing fitted furniture", "Our portfolio includes an office wardrobe with tailored shelving and hanging space, a fitted wall feature and a trophy display unit. These show examples of fitted furniture rather than a promise that every room can use the same layout."],
  ], questions: [["Can you work with an awkward space?", "Send photographs and dimensions. We review the constraints before proposing a fitted storage arrangement."], ["What should I include in an enquiry?", "Your postcode, room photographs, approximate dimensions and a description of the storage you need."]] },
  { path: "/kitchen-renovations", title: "Kitchen Renovations in Northern Ireland", image: "/projects/kitchen46.JPG", description: "Kitchen renovation and refurbishment enquiries for homes, rentals and HMO projects across Northern Ireland.", intro: "A kitchen renovation can involve more than replacing cabinets. DC Joinery discusses the preparation, installation and finishing needed to bring the room together.", sections: [
    ["Review the existing room", "Tell us what you want to keep, replace or improve. Photographs and plans help us discuss layout, storage, appliance spaces and the preparation needed."],
    ["Preparation and finishing", "Our recent portfolio includes tile removal, self-levelling and herringbone flooring alongside kitchen installation. The preparation, flooring and tiling for your project are included only where agreed in the scope."],
    ["Homes and investment projects", "We have worked on private residential kitchens, rental refurbishments and HMO upgrades. Access, usability, durability and trade coordination are discussed for each project."],
  ], questions: [["Can I keep the existing layout?", "We can review that option with you. Condition, services and the proposed kitchen determine what is practical."], ["Can you quote from photographs alone?", "Photographs help start the discussion, but accurate plans and a site review may be needed before confirming the quotation."]] },
  { path: "/bespoke-kitchens", title: "Bespoke Kitchen Installation in Northern Ireland", image: "/projects/kitchen5.jpg", description: "Installation and project coordination for bespoke kitchens, tailored layouts and finishing details in Northern Ireland.", intro: "A bespoke kitchen needs careful coordination between the room, cabinet design, appliances and installation. We discuss the plans and fitting details with you and the chosen supplier.", sections: [
    ["Review the design", "Cabinet dimensions, clearances, panels and appliance specifications need to work together. Supplier drawings help establish the installation requirements before fitting begins."],
    ["Fitting and finishing", "We focus on alignment, worktop interfaces and finishing details. Our portfolio includes bespoke kitchen installations for rental and HMO projects."],
    ["Supply and trade coordination", "Discuss whether you need installation only or help with supply and project coordination. The agreed quotation identifies the work, supplier responsibilities and specialist trades involved."],
  ], questions: [["Do you manufacture every bespoke kitchen yourselves?", "The supply and installation arrangement is agreed for each project. Contact us with your plans to discuss the supplier and fitting requirements."], ["Can you install a kitchen from an independent supplier?", "Send the drawings and specifications so we can review the installation and coordination needed."]] },
] as const;
